### ISSUE TITLE
Readme ergänzen

### ISSUE THREAD

**Issue by staabm** [redaxo/clockwork-app#2]
Im redaxo branch eine readme hinterlegen die kurz beschreibt worin das redaxo customizing besteht und wie man damit arbeiten muss

Wichtig ist auch: wie erzeugt man hier ein release und wie ist der prozess dieses dann nach redaxo zu bekommen

**Comment by bloep** [comment]
ergänzt mit https://github.com/redaxo/clockwork-app/commit/95ccd366335e15d8035a81d7b6a5f6cdab77e83b

Anleitung fürs lokale entwickeln, updaten im REDAXO repo ergänzt.
Zusätzlich einen Bereich ergänzt, um die spezifischen Änderungen festzuhalten.

**Comment by staabm** [comment]
Danke !
